name: formal

on:
  [push, workflow_dispatch]

jobs:
  formal:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install oss-cad-suite
        uses: YosysHQ/setup-oss-cad-suite@v3

      - name: Run formal tests
        working_directory: ./src
        shell: bash
        run: |
          sby -f formal_bmc.sby
          sby -f formal_prove.sby
          sby -f formal_cover.sby

